# Generated by Django 5.1.2 on 2024-11-11 10:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=250, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='Provinces/images')),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('provinces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UzAmazingTravel.provinces')),
            ],
        ),
    ]
