# Generated by Django 5.1.2 on 2024-11-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UzAmazingTravel', '0003_provinces_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provinces',
            name='info',
        ),
        migrations.AddField(
            model_name='provinces',
            name='culture_and_traditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provinces',
            name='economy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provinces',
            name='geography',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provinces',
            name='nature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provinces',
            name='population',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provinces',
            name='story',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
