# Generated by Django 5.1.2 on 2024-11-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UzAmazingTravel', '0004_remove_provinces_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinces',
            name='culture_and_traditions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='economy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='geography',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='nature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='population',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='story',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
